### ISSUE TITLE
Following docs for component based Kodein results in NPE

### ISSUE THREAD

**Issue by eygraber** [Kodein-Framework/Kodein-DI#141]
If I follow the [instructions here](https://kodein.org/Kodein-DI/?5.2/android#_component_based_kodein) for setting up a component based Kodein, I get an NPE saying that `getApplicationContext` was called on a null reference.

Here's the code:

```
abstract class MyFragment: Fragment(), KodeinAware {
  private val parentKodein: Kodein by closestKodein()

  override val kodein = Kodein {
    extend(parentKodein)

    bind<Fragment>() with provider {  this@MyFragment }
  }
}
```

The issue is solved by changing `kodein` to `override val kodein = Kodein.lazy { ... }`

**Comment by eygraber** [comment]
The stacktrace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 25869
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.MainView}: kotlin.KotlinNullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: kotlin.KotlinNullPointerException
        at org.kodein.di.android.support.ClosestKt$closestKodein$1.invoke(closest.kt:11)
        at org.kodein.di.android.support.ClosestKt$closestKodein$1.invoke(Unknown Source:0)
        at org.kodein.di.android.ClosestKodeinPropertyDelegateProvider$provideDelegate$1.invoke(closest.kt:41)
        at org.kodein.di.android.ClosestKodeinPropertyDelegateProvider$provideDelegate$1.invoke(closest.kt:40)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.myapp.MyFragment.getParentKodein(Unknown Source:7)
        at com.myapp.MyFragment.access$getParentKodein$p(MyFragment.kt:11)
        at com.myapp.MyFragment$kodein$1.invoke(MyFragment.kt:15)
        at com.myapp.MyFragment$kodein$1.invoke(MyFragment.kt:11)
        at org.kodein.di.internal.KodeinImpl$Companion.newBuilder(KodeinImpl.kt:22)
        at org.kodein.di.internal.KodeinImpl$Companion.access$newBuilder(KodeinImpl.kt:21)
        at org.kodein.di.internal.KodeinImpl.<init>(KodeinImpl.kt:19)
        at org.kodein.di.Kodein$Companion.invoke(Kodein.kt:423)
        at org.kodein.di.Kodein$Companion.invoke$default(Kodein.kt:423)
        at com.myapp.MyFragment.<init>(MyFragment.kt:14)
        at com.myapp.my_profile.MyProfileView.<init>(MyProfileView.kt:28)
        at com.myapp.ui.UiManagerImpl.commit(UiManager.kt:80)
        at com.myapp.main.MainPresenter.initialize(MainPresenter.kt:64)
        at com.myapp.main.MainView.onCreate(MainView.kt:74)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by SalomonBrys** [comment]
You're right :)
The doc has been updated and will be shown

**Comment by mpetuska** [comment]
Had the same race condition with DI + DI.Module.
