### ISSUE TITLE
Importing AndroidXModule or AndroidModule causes crash

### ISSUE THREAD

**Issue by miloszkleszczewski** [Kodein-Framework/Kodein-DI#179]
This is the main application code. Let me note, it is declared in AndroidManifest.
```
class MainApplication: Application(), KodeinAware{
    override val kodein = Kodein.lazy{

        bind() from singleton {TestClass()}
        import(androidXModule(this@MainApplication))

    }
}
```
When I'm trying to access TestClass() instance from an Activity (which is KodeinAware) :
```
    override val kodein by closestKodein()
    private val test: TestClass by instance()
```
TestClass() is: 
```
class TestClass{
    val x = 5
}
```
And then, in onCreate for example

`val x  = test.x`

It crashes. When import of androidXModule is commented out, it works properly. Obviously, no functionality of androidXModule is used here, but I need it for other instances. This was tested on a bare-bones project with nothing but a MainActivity, TestClass and custom MainApplication. 
Here is the logcat exception:
```
2019-02-01 19:16:12.472 20895-20895/com.x.x.x E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.x.x.x, PID: 20895
    java.lang.NoSuchMethodError: No static method importOnce$default(Lorg/kodein/di/Kodein$Builder;Lorg/kodein/di/Kodein$Module;ZILjava/lang/Object;)V in class Lorg/kodein/di/Kodein$Builder; or its super classes (declaration of 'org.kodein.di.Kodein$Builder' appears in /data/app/com.x.x.x-Y3HhfW-NAj95_Rb4y3S51A==/split_lib_dependencies_apk.apk)
        at org.kodein.di.android.x.ModuleKt$androidXModule$1.invoke(module.kt:17)
        at org.kodein.di.android.x.ModuleKt$androidXModule$1.invoke(Unknown Source:2)
        at org.kodein.di.internal.KodeinBuilderImpl.import(KodeinBuilderImpl.kt:46)
        at org.kodein.di.Kodein$Builder$DefaultImpls.import$default(Kodein.kt:301)
        at com.x.x.x.MainApplication$kodein$1.invoke(MainApplication.kt:21)
        at com.x.x.x.MainApplication$kodein$1.invoke(MainApplication.kt:15)
        at org.kodein.di.internal.KodeinImpl$Companion.newBuilder(KodeinImpl.kt:22)
        at org.kodein.di.internal.KodeinImpl$Companion.access$newBuilder(KodeinImpl.kt:21)
        at org.kodein.di.internal.KodeinImpl.<init>(KodeinImpl.kt:19)
        at org.kodein.di.Kodein$Companion$lazy$1.invoke(Kodein.kt:414)
        at org.kodein.di.Kodein$Companion$lazy$1.invoke(Kodein.kt:396)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.kodein.di.LazyKodein.getBaseKodein(Unknown Source:7)
        at org.kodein.di.LazyKodein.getContainer(lateinit.kt:29)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(KodeinAware.kt:157)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(Unknown Source:8)
        at org.kodein.di.KodeinProperty$provideDelegate$1.invoke(properties.kt:42)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.x.x..MainActivity.getTest(Unknown Source:25)
        at com.x.x.x.MainActivity.onCreate(MainActivity.kt:22)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
"at com.x.x.x.MainApplication$kodein$1.invoke(MainApplication.kt:21)" line is pointing to androidXModule import inside MainApplication

**Comment by SalomonBrys** [comment]
Can I see your gradle build file ?
This error can be the result of:

* kodein-android and kodein-core being different versions.
* you imported kodein-android, but not kodein-erased or kodein-generic.

**Comment by SalomonBrys** [comment]
This is more of a help needed than a bug.
This will be answered here: https://stackoverflow.com/questions/54493585/importing-androidxmodule-in-kodein-causes-a-crash

**Comment by Drjacky** [comment]
@SalomonBrys The link is broken.

**Shared build.gradle**:
```kotlin
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

val buildToolsVersion: String by project
val kotlinVersion: String by extra
val reactiveVersion: String by extra
val kotlinSerializationVersion: String by extra
val ktorVersion: String by extra
val coroutinesVersion: String by extra
val kodeinVersion: String by extra

plugins {
    id("com.android.library")
    kotlin("multiplatform")
    kotlin("plugin.serialization") version "1.4.0" //org.jetbrains.kotlin.config.KotlinCompilerVersion.VERSION
}

android {
    compileSdkVersion(29)
    buildToolsVersion = buildToolsVersion
    defaultConfig {
        minSdkVersion(21)
        targetSdkVersion(29)
    }
    sourceSets {
        val main by getting {
            java.srcDirs("src/androidMain/kotlin")
            manifest.srcFile("src/androidMain/AndroidManifest.xml")
            res.srcDirs("src/androidMain/res")
        }
    }
}

kotlin {
    jvm()
    //jvm("android")
    android()

    //select iOS target platform depending on the Xcode environment variables
    val iOSTarget: (String, KotlinNativeTarget.() -> Unit) -> KotlinNativeTarget =
        if (System.getenv("SDK_NAME")?.startsWith("iphoneos") == true)
            ::iosArm64
        else
            ::iosX64

    iOSTarget("ios") {
        binaries {
            framework {
                baseName = "shared"
                freeCompilerArgs += "-Xobjc-generics"
            }
        }
    }

    sourceSets {
        val soloMain by creating {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:$kotlinSerializationVersion")
            }
        }
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlin:kotlin-stdlib")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-common:$coroutinesVersion")
                implementation("com.badoo.reaktive:reaktive:$reactiveVersion")
                //implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.20.0")
                implementation("io.ktor:ktor-client-core:$ktorVersion")
                implementation("io.ktor:ktor-client-serialization:$ktorVersion")
                implementation("io.ktor:ktor-client-logging:$ktorVersion")
                implementation("org.kodein.di:kodein-di:$kodeinVersion")
            }
        }

        val mobileMain by creating {
            dependsOn(commonMain)
        }

        val jvmMain by getting {
            dependencies {
                api("org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion")
                api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion")
                api("org.jetbrains.kotlinx:kotlinx-serialization-runtime:1.0-M1-1.4.0-rc")
                api("io.ktor:ktor-client-serialization-jvm:$ktorVersion")
                api("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
                api("io.ktor:ktor-client-core-jvm:$ktorVersion")
                api("io.ktor:ktor-client-logging-jvm:$ktorVersion")
            }
        }

        val androidMain by getting {
            dependsOn(mobileMain)
            dependsOn(jvmMain)
        }

        val iosMain by getting {
            dependsOn(mobileMain)
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$coroutinesVersion")
                //implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:0.20.0")
                implementation("io.ktor:ktor-client-ios:$ktorVersion")
                implementation("io.ktor:ktor-client-serialization-native:$ktorVersion")
                implementation("io.ktor:ktor-client-logging-native:$ktorVersion")
            }
        }

        all {
            languageSettings.useExperimentalAnnotation("kotlin.RequiresOptIn")
        }
    }

}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

val packForXcode by tasks.creating(Sync::class) {
    val targetDir = File(buildDir, "xcode-frameworks")
    //selecting the right configuration for the iOS framework depending on the Xcode environment variables
    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val framework = kotlin.targets.getByName<KotlinNativeTarget>("ios").binaries.getFramework(mode)

    inputs.property("mode", mode)
    dependsOn(framework.linkTask)

    from({ framework.outputDirectory })
    into(targetDir)

    /// generate a helpful ./gradlew wrapper with embedded Java path
    doLast {
        val gradlew = File(targetDir, "gradlew")
        gradlew.writeText("#!/bin/bash\nexport 'JAVA_HOME=${System.getProperty("java.home")}'\ncd '${rootProject.rootDir}'\n./gradlew \$@\n")
        gradlew.setExecutable(true)
    }
}

tasks.getByName("build").dependsOn(packForXcode)
```

**DI.kt**:
```kotlin
@ThreadLocal
object Di {

    val di = DI.lazy {
        bind<HttpClient>() with singleton {
            HttpClient {
                install(JsonFeature) {
                    serializer = KotlinxSerializer()
                }
                install(Logging) {
                    logger = Logger.DEFAULT
                    level = LogLevel.ALL
                }
            }
...
        }
```

kodeinVersion=7.0.0

**Comment by romainbsl** [comment]
This seems to be a serialization issue, most of the API has been changed.
However, Kodein-DI `7.0.0` does not work for kotlin 1.4+ checkout our dev repo:
https://bintray.com/kodein-framework/kodein-dev
with the version `7.1.0-master-87`
