### ISSUE TITLE
closestKodein() in AndroidX AppCompatActivity throws NullPointerException

### ISSUE THREAD

**Issue by amirg1992** [Kodein-Framework/Kodein-DI#236]
I'm using AndroidX and following frameworks:
```
    implementation "androidx.appcompat:appcompat:1.1.0-rc01"
    implementation "androidx.core:core-ktx:1.2.0-alpha02"
    implementation "org.kodein.di:kodein-di-generic-jvm:6.3.2"
    implementation "org.kodein.di:kodein-di-framework-android-x:6.3.2"
```

And this is how I'm using it:
```
import org.kodein.di.android.closestKodein

open class BaseActivity : AppCompatActivity(), KodeinAware {
    override val kodein: Kodein by closestKodein()
```

I'm using `import org.kodein.di.android.x.closestKodein` in fragments but it's not working in `AppCompatActivity`

And here is the stack trace:
```
ava.lang.RuntimeException: Unable to start activity ComponentInfo{com.ghaleh.templatetwo/main.BaseActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3364)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:116)
        at org.kodein.di.android.ClosestKt.kodein(closest.kt:25)
        at org.kodein.di.android.ClosestKt.access$kodein(closest.kt:1)
        at org.kodein.di.android.ContextKodeinPropertyDelegateProvider$provideDelegate$1.invoke(closest.kt:39)
        at org.kodein.di.android.ContextKodeinPropertyDelegateProvider$provideDelegate$1.invoke(closest.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at main.BaseActivity.getKodein(Unknown Source:7)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(KodeinAware.kt:176)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(Unknown Source:4)
        at org.kodein.di.KodeinProperty$provideDelegate$1.invoke(properties.kt:42)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at main.BaseActivity.getAppClass(Unknown Source:7)
        at main.BaseActivity.attachBaseContext(BaseActivity.kt:60)
        at android.app.Activity.attach(Activity.java:7361)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3320)
```

**Comment by romainbsl** [comment]
Hi, how do you use your `open class BaseActivity` ? I can't reproduce the issue.

**Comment by amirg1992** [comment]
BaseActivity is an extention of AppCompatActivity

**Comment by romainbsl** [comment]
Yes, but as its `open`, so my guess was maybe this is extended elsewhere. Or, is `BaseActivity` your main activity ? Or even, can you provide a reproducable case ?

**Comment by amirg1992** [comment]
Yes, `BaseActivity` is app's main and only activity. I do not have access to codes now. I will give you more information as soon as possible.

**Comment by amirg1992** [comment]
The error is thrown on API 28. it's working fine on API 21 (Emulator).

**Comment by romainbsl** [comment]
Still no luck to reproduce your issue, here is my sample project: 
https://github.com/romainbsl/kodein-di-issue-236

can you give it a try and tell me what to change to reproduce your case ?

**Comment by amirg1992** [comment]
The problem is gone now. I think it was related to Android Studio version or the plugin versions. This is the only thing that is changed since when I opened the issue.
Kodein has no problem!
Thank you!
