### ISSUE TITLE
android.app.Application cannot be cast to org.kodein.di.KodeinAware

### ISSUE THREAD

**Issue by forntoh** [Kodein-Framework/Kodein-DI#288]
I get the following error when the app starts, I've tried to trace it but to no avail
```kotlin
2020-02-17 12:22:18.289 16962-16962/ga.forntoh.bableschool E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ga.forntoh.bableschool, PID: 16962
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ga.forntoh.bableschool/ga.forntoh.bableschool.ui.category.CategoriesActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to org.kodein.di.KodeinAware
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to org.kodein.di.KodeinAware
        at org.kodein.di.android.ClosestKt.kodein(closest.kt:25)
        at org.kodein.di.android.ClosestKt.access$kodein(closest.kt:1)
        at org.kodein.di.android.ContextKodeinPropertyDelegateProvider$provideDelegate$1.invoke(closest.kt:39)
        at org.kodein.di.android.ContextKodeinPropertyDelegateProvider$provideDelegate$1.invoke(closest.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at ga.forntoh.bableschool.ui.base.BaseActivity.getKodein(Unknown Source:7)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(KodeinAware.kt:176)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(Unknown Source:4)
        at org.kodein.di.KodeinProperty$provideDelegate$1.invoke(properties.kt:42)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at ga.forntoh.bableschool.ui.base.BaseActivity.getViewModelFactory(Unknown Source:7)
        at ga.forntoh.bableschool.ui.base.BaseActivity.onCreate(BaseActivity.kt:38)
        at ga.forntoh.bableschool.ui.category.CategoriesActivity.onCreate(CategoriesActivity.kt:34)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

Gradle
```gradle
implementation "org.kodein.di:kodein-di-generic-jvm:6.5.0"
implementation "org.kodein.di:kodein-di-framework-android-x:6.5.0"
```
Application
```kotlin
class App : MultiDexApplication(), KodeinAware {

    override val kodein by Kodein.lazy {
        import(androidXModule(this@App))
        ...
```
Manifest
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="ga.forntoh.bableschool">

    ...

    <application
        android:name=".App"
        ...
```
Activity
```kotlin
open class BaseActivity : ScopedActivity(), KodeinAware {

    override val kodein by closestKodein()

    private val viewModelFactory: ProfileViewModelFactory by instance()

    ...

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        viewModel = ViewModelProvider(this, viewModelFactory).get(ProfileViewModel::class.java)

        ...

    }

    ...

```

**Comment by romainbsl** [comment]
Hi, 

My guess would be that when you are using the function `closestKodein()`, Kodein-DI finds the `applicationContext` from the `android.app.Application`, but for some reason this context cannot be cast to `KodeinAware`.

Is your Application extending `android.app.Application` somehow? 
If not you should consider it, and then declare your bindings in it.

**Comment by forntoh** [comment]
> Hi,
> 
> My guess would be that when you are using the function `closestKodein()`, Kodein-DI finds the `applicationContext` from the `android.app.Application`, but for some reason, this context cannot be cast to `KodeinAware`.
> 
> Is your Application extending `android.app.Application` somehow?
> If not you should consider it, and then declare your bindings in it.

My application extends `MultiDexApplication` and implements `Kodeinaware`

MultidexApplication inturn extends `android.app.Application`

**Comment by romainbsl** [comment]
Maybe you could try to force the `App` class to be use as the application context.
`override val kodein by lazy { (applicationContext as App).kodein }`

**Comment by forntoh** [comment]
> Maybe you could try to force the `App` class to be used as the application context.
> `override val kodein by lazy { (applicationContext as App).kodein }`

I tried that too, but still not working 😞.

**Comment by romainbsl** [comment]
Do you have a reproducible case / repo that I could try ?

**Comment by forntoh** [comment]
> Maybe you could try to force the `App` class to be used as the application context.
> `override val kodein by lazy { (applicationContext as App).kodein }`

Oh... What I tried was `override val kodein by lazy { (applicationContext as KodeinAware).kodein }`
But `(applicationContext as App).kodein`, works 😊

### Question ⬇️
Please can you tell me why forcing it works now, because since the debut of the project I have used `closestKodein()` and it worked, untill now.

**Comment by romainbsl** [comment]
It certainly depends on which class you used `closestKodein()`, as it is an extension function for different UI components. But in the end, the goal is always to find the nearest `applicationContext` that is carrying a Kodein instance. Maybe this is working somewhere else but in this particular case, it doesn't. I'm not an Android expert, thus I do not know every component and their differences.

Did you have a MultiDexApplication since the beginning?

**Comment by forntoh** [comment]
> Did you have a MultiDexApplication since the beginning?

At a certain point, I changed to `MultiDexApplication` it kept working.
