### ISSUE TITLE
Can't get any object on a BroadcastReceiver in Kodein 7.0

### ISSUE THREAD

**Issue by pokk** [Kodein-Framework/Kodein-DI#323]
This is my broadcastreceiver and would like to get `DownloadManager`

```kotlin
class DownloadReceiver : BroadcastReceiver(), DIAware {
    override val di by lazy { (MyApplication.appContext as MyApplication).di }

    override fun onReceive(context: Context?, intent: Intent?) {
        if (context == null) return
        val action = intent?.action ?: return
        val downloadManager by di.instance<DownloadManager>()
        if (DownloadManager.ACTION_DOWNLOAD_COMPLETE == action) {
            val downloadId = intent.getLongExtra(DownloadManager.EXTRA_DOWNLOAD_ID, -1)
            val cursor = downloadManager.query(Query().setFilterById(downloadId))  // ⇐ here will happen crash
            if (cursor.moveToFirst()) {
                val title = cursor.getString(cursor.getColumnIndex(DownloadManager.COLUMN_TITLE))
            }
        }
    }
}
```

This is the error message happened
```
java.lang.RuntimeException: Unable to start receiver myapp.com.services.DownloadReceiver: org.kodein.di.DI$NotFoundException: No binding found for bind<android.app.DownloadManager>() with ? { ? }
    Available bindings for this type:
            module ⁣androidModule {
                bind<android.app.DownloadManager>() with contexted<android.content.Context>().provider { android.app.DownloadManager }
            }
    Registered in this DI container:
            ...
            module ⁣androidModule {
                bind<android.os.storage.StorageManager>() with contexted<android.content.Context>().provider { android.os.storage.StorageManager }
                bind<android.content.SharedPreferences>() with contexted<android.content.Context>().provider { android.content.SharedPreferences }
                bind<android.content.SharedPreferences>() with contexted<android.content.Context>().factory { kotlin.String -> android.content.SharedPreferences }
                bind<android.media.AudioManager>() with contexted<android.content.Context>().provider { android.media.AudioManager }
                bind<android.net.wifi.WifiManager>() with contexted<android.content.Context>().provider { android.net.wifi.WifiManager }
                bind<android.telephony.CarrierConfigManager>() with contexted<android.content.Context>().provider { android.telephony.CarrierConfigManager }
                bind<android.content.pm.ShortcutManager>() with contexted<android.content.Context>().provider { android.content.pm.ShortcutManager }
                bind<android.net.ConnectivityManager>() with contexted<android.content.Context>().provider { android.net.ConnectivityManager }
                bind<android.os.UserManager>() with contexted<android.content.Context>().provider { android.os.UserManager }
                bind<android.os.HardwarePropertiesManager>() with contexted<android.content.Context>().provider { android.os.HardwarePropertiesManager }
                bind<android.content.pm.ApplicationInfo>() with contexted<android.content.Context>().provider { android.content.pm.ApplicationInfo }
                bind<android.appwidget.AppWidgetManager>() with contexted<android.content.Context>().provider { android.appwidget.AppWidgetManager }
                bind<android.view.WindowManager>() with contexted<android.content.Context>().provider { android.view.WindowManager }
                bind<android.location.LocationManager>() with contexted<android.content.Context>().provider { android.location.LocationManager }
                bind<android.app.AppOpsManager>() with contexted<android.content.Context>().provider { android.app.AppOpsManager }
1599451665.542 14716-14716 E:             bind<android.hardware.fingerprint.FingerprintManager>() with contexted<android.content.Context>().provider { android.hardware.fingerprint.FingerprintManager }
                bind<android.app.AlarmManager>() with contexted<android.content.Context>().provider { android.app.AlarmManager }
                bind<kotlin.String>(tag = "packageCodePath") with contexted<android.content.Context>().provider { kotlin.String }
                bind<android.app.ActivityManager>() with contexted<android.content.Context>().provider { android.app.ActivityManager }
                bind<android.os.PowerManager>() with contexted<android.content.Context>().provider { android.os.PowerManager }
                bind<android.content.pm.PackageManager>() with contexted<android.content.Context>().provider { android.content.pm.PackageManager }
                bind<android.app.UiModeManager>() with contexted<android.content.Context>().provider { android.app.UiModeManager }
                bind<android.app.Application>() with provider { android.app.Application }
                bind<android.media.tv.TvInputManager>() with contexted<android.content.Context>().provider { android.media.tv.TvInputManager }
                bind<android.hardware.camera2.CameraManager>() with contexted<android.content.Context>().provider { android.hardware.camera2.CameraManager }
                bind<android.media.session.MediaSessionManager>() with contexted<android.content.Context>().provider { android.media.session.MediaSessionManager }
                bind<android.os.DropBoxManager>() with contexted<android.content.Context>().provider { android.os.DropBoxManager }
                bind<android.net.wifi.p2p.WifiP2pManager>() with contexted<android.content.Context>().provider { android.net.wifi.p2p.WifiP2pManager }
                bind<java.io.File>(tag = "obb") with contexted<android.content.Context>().provider { java.io.File }
                bind<kotlin.String>(tag = "packageName") with contexted<android.content.Context>().provider { kotlin.String }
                bind<android.telephony.SubscriptionManager>() with contexted<android.content.Context>().provider { android.telephony.SubscriptionManager }
                bind<android.hardware.display.DisplayManager>() with contexted<android.content.Context>().provider { android.hardware.display.DisplayManager }
                bind<android.app.job.JobScheduler>() with contexted<android.content.Context>().provider { android.app.job.JobScheduler }
                bind<android.view.textservice.TextServicesManager>() with contexted<android.content.Context>().provider { android.view.textservice.TextServicesManager }
                bind<android.app.usage.UsageStatsManager>() with contexted<android.content.Context>().provider { android.app.usage.UsageStatsManager }
                bind<android.media.MediaRouter>() with contexted<android.content.Context>().provider { android.media.MediaRouter }
                bind<android.telephony.TelephonyManager>() with contexted<android.content.Context>().provider { android.telephony.TelephonyManager }
                bind<android.os.Vibrator>() with contexted<android.content.Context>().provider { android.os.Vibrator }
                bind<android.telecom.TelecomManager>() with contexted<android.content.Context>().provider { android.telecom.TelecomManager }
                bind<android.app.NotificationManager>() with contexted<android.content.Context>().provider { android.app.NotificationManager }
                bind<android.view.accessibility.AccessibilityManager>() with contexted<android.content.Context>().provider { android.view.accessibility.AccessibilityManager }
                bind<java.io.File>(tag = "externalCache") with contexted<android.content.Context>().provider { java.io.File }
                bind<android.app.DownloadManager>() with contexted<android.content.Context>().provider { android.app.DownloadManager }
                bind<android.print.PrintManager>() with contexted<android.content.Context>().provider { android.print.PrintManager }
1599451665.543 14716-14716 E:             bind<kotlin.String>(tag = "packageResourcePath") with contexted<android.content.Context>().provider { kotlin.String }
                bind<android.hardware.input.InputManager>() with contexted<android.content.Context>().provider { android.hardware.input.InputManager }
                bind<java.io.File>(tag = "files") with contexted<android.content.Context>().provider { java.io.File }
                bind<android.content.pm.LauncherApps>() with contexted<android.content.Context>().provider { android.content.pm.LauncherApps }
                bind<android.view.accessibility.CaptioningManager>() with contexted<android.content.Context>().provider { android.view.accessibility.CaptioningManager }
                bind<android.content.res.AssetManager>() with contexted<android.content.Context>().provider { android.content.res.AssetManager }
                bind<android.app.admin.DevicePolicyManager>() with contexted<android.content.Context>().provider { android.app.admin.DevicePolicyManager }
                bind<android.app.SearchManager>() with contexted<android.content.Context>().provider { android.app.SearchManager }
                bind<android.app.WallpaperManager>() with contexted<android.content.Context>().provider { android.app.WallpaperManager }
                bind<android.view.LayoutInflater>() with contexted<android.content.Context>().provider { android.view.LayoutInflater }
                bind<android.accounts.AccountManager>() with contexted<android.content.Context>().provider { android.accounts.AccountManager }
                bind<android.media.projection.MediaProjectionManager>() with contexted<android.content.Context>().provider { android.media.projection.MediaProjectionManager }
                bind<android.content.res.Resources>() with contexted<android.content.Context>().provider { android.content.res.Resources }
                bind<android.os.health.SystemHealthManager>() with contexted<android.content.Context>().provider { android.os.health.SystemHealthManager }
                bind<android.hardware.usb.UsbManager>() with contexted<android.content.Context>().provider { android.hardware.usb.UsbManager }
                bind<android.content.res.Resources.Theme>() with contexted<android.content.Context>().provider { android.content.res.Resources.Theme }
                bind<android.content.ContentResolver>() with contexted<android.content.Context>().provider { android.content.ContentResolver }
                bind<android.content.RestrictionsManager>() with contexted<android.content.Context>().provider { android.content.RestrictionsManager }
                bind<android.hardware.SensorManager>() with contexted<android.content.Context>().provider { android.hardware.SensorManager }
                bind<android.content.ClipboardManager>() with contexted<android.content.Context>().provider { android.content.ClipboardManager }
                bind<java.io.File>(tag = "cache") with contexted<android.content.Context>().provider { java.io.File }
                bind<android.bluetooth.BluetoothManager>() with contexted<android.content.Context>().provider { android.bluetooth.BluetoothManager }
                bind<android.nfc.NfcManager>() with contexted<android.content.Context>().provider { android.nfc.NfcManager }
                bind<android.net.nsd.NsdManager>() with contexted<android.content.Context>().provider { android.net.nsd.NsdManager }
                bind<android.app.usage.NetworkStatsManager>() with contexted<android.content.Context>().provider { android.app.usage.NetworkStatsManager }
                bind<android.hardware.ConsumerIrManager>() with contexted<android.content.Context>().provider { android.hardware.ConsumerIrManager }
                bind<android.os.BatteryManager>() with contexted<android.content.Context>().provider { android.os.BatteryManager }
                bind<android.view.inputmethod.InputMethodManager>() with contexted<android.content.Context>().provider { android.view.inputmethod.InputMethodManager }
1599451665.552 14716-14716 E:             bind<android.app.KeyguardManager>() with contexted<android.content.Context>().provider { android.app.KeyguardManager }
                bind<android.os.Looper>() with contexted<android.content.Context>().provider { android.os.Looper }
                bind<android.media.midi.MidiManager>() with contexted<android.content.Context>().provider { android.media.midi.MidiManager }
            }
    
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

		...
    
        at org.kodein.di.internal.DIContainerImpl.factory(DIContainerImpl.kt:188)
        at org.kodein.di.DIContainer$DefaultImpls.factory$default(DIContainer.kt:35)
        at org.kodein.di.DIContainer$DefaultImpls.provider(DIContainer.kt:79)
        at org.kodein.di.internal.DIContainerImpl.provider(DIContainerImpl.kt:9)
        at org.kodein.di.DIContainer$DefaultImpls.provider$default(DIContainer.kt:78)
        at org.kodein.di.DIAwareKt$Instance$1.invoke(DIAware.kt:190)
        at org.kodein.di.DIAwareKt$Instance$1.invoke(Unknown Source:4)
        at org.kodein.di.DIProperty$provideDelegate$1.invoke(properties.kt:51)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at myapp.com.services.DownloadReceiver.onReceive(DownloadReceiver.kt:88)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)
        	... 8 more
```

```kotlin
class MyApplication : Application(), DIAware {
    companion object {
        lateinit var appContext: Context
            private set
    }

    init {
        appContext = this
        DI.defaultFullDescriptionOnError = true
    }

    override val di = Dispatcher.importIntoApp(this)
}

object Dispatcher {
    fun importIntoApp(app: Application) = DI.lazy {
        import(androidXModule(app))
    }
}
```

Register the broadcastreceiever at `AndroidManifest.xml`

```xml
        <receiver android:name=".services.DownloadReceiver">
            <intent-filter>
                <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
            </intent-filter>
        </receiver>
```

I have also tried passing the DI into and register the broadcastreceiver after the app started. The same error happens.
Could you help me on how to fix this? thank you so much

**Comment by romainbsl** [comment]
This is because your binding is defined on a context:  `with contexted<android.content.Context>()`

but the retrieving is done without any context: `val downloadManager by di.instance<DownloadManager>()`

Either you remove the context from your binding, either you use a context:
- by retrieving on the context  `val downloadManager by di.on(YOUR_CONTEXT).instance<DownloadManager>()`
- by overriding the context of the DIAware interface

**Comment by pokk** [comment]
@romainbsl 
Thank you so much for your hint.
I used your solution, it does work well!
```kotlin
val downloadManager by di.on(MyApplication.appContext).instance<DownloadManager>()
```

Just wondering, I am using the same way for overriding the context of DIAware at other class
```kotlin
override val di by lazy { (MyApplication.appContext as MyApplication).di }
```
but only there has this issue, do you have any idea?

**Comment by romainbsl** [comment]
As you are in a DIAware object, you can do something like:

```kotlin
override val diContext = diContext(YOUR_CONTEXT) 
```
