### ISSUE TITLE
DIAware AndroidViewModel causes Backend Internal error: Exception during file facade code generation

### ISSUE THREAD

**Issue by tom5079** [Kodein-Framework/Kodein-DI#347]
Kotlin 1.4.21
Kodein DI Framework AndroidX 7.1.0

```kotlin
package com.example.kodein.error

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import org.kodein.di.DIAware

class MyViewModel(app: Application) : AndroidViewModel(app), DIAware {

    override val di by di()

}
```

Compiling the exact same code in the [documentation](https://docs.kodein.org/kodein-di/7.1/framework/android.html#_view_models) causes
`e: java.lang.IllegalStateException: Backend Internal error: Exception during file facade code generation`

Full stacktrace:
```
java.lang.IllegalStateException: Backend Internal error: Exception during file facade code generation
File being compiled: file://D:/Workspace/KodeinError/app/src/main/java/com/example/kodein/error/ViewModel.kt
The root cause java.lang.IllegalStateException was thrown at: org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$typeMappingConfiguration$1.processErrorType(KotlinTypeMapper.kt:109)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:78)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:88)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:67)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:647)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:210)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:162)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:371)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:105)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:249)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:38)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:80)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:602)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1644)
	at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Error type encountered: [ERROR : <ERROR FUNCTION RETURN TYPE>] (DeferredType).
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$typeMappingConfiguration$1.processErrorType(KotlinTypeMapper.kt:109)
	at org.jetbrains.kotlin.load.kotlin.TypeSignatureMappingKt.mapType(typeSignatureMapping.kt:104)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.kt:261)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapReturnType(KotlinTypeMapper.kt:196)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapReturnType(KotlinTypeMapper.kt:190)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapSignatureWithCustomParameters(KotlinTypeMapper.kt:853)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapSignature(KotlinTypeMapper.kt:768)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapSignature(KotlinTypeMapper.kt:716)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapPropertyReferenceSignature(KotlinTypeMapper.kt:679)
	at org.jetbrains.kotlin.codegen.CallableReferenceUtilKt.getSignatureString(callableReferenceUtil.kt:209)
	at org.jetbrains.kotlin.codegen.CallableReferenceUtilKt.generatePropertyReferenceSignature(callableReferenceUtil.kt:176)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generatePropertyReference(MemberCodegen.java:684)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generatePropertyMetadataArrayFieldIfNeeded(MemberCodegen.java:655)
	at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateSyntheticPartsBeforeBody(ImplementationBodyCodegen.java:403)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:126)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:138)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:70)
	... 36 more
```

**Comment by tom5079** [comment]
Found out that `by di()` does not work in general even in Activities, Fragments, etc.
`closestDI()` works fine.

**Comment by tom5079** [comment]
Turns out that there are multiple extension functions for each class and you have to import the correct one.

**Comment by tscott0** [comment]
Thank you @tom5079 ! 

Strangely the compiler is happy with this line, despite `di` not being imported from kodein. No issues highlighted on this line in Android Studio 4.1.1 and nothing in the stacktrace. We tried with both 1.4.21 and 1.4.30-M1. I suspect this might be a kotlin compiler/plugin issue. 
```kotlin
override val di by di()
```

As you suggested, it can be changed to `closestDI()` or by explicitly referring to the right package like this:
```kotlin
override val di by org.kodein.di.android.di()
```

Or just explicityly importing the correct one, like this:
```kotlin
import org.kodein.di.android.di
```

The documentation we were following is [here](https://docs.kodein.org/kodein-di/7.2/framework/android.html#_android_module), but doesn't show the imports. 

The Kodein-Samples example [does demonstrate how to do the import properly](https://github.com/Kodein-Framework/Kodein-Samples/blob/master/di/coffee-maker/android/src/main/java/org/kodein/di/samples/MainActivity.kt#L7) but it's very different, presumably as it's not a pure Android project.

A couple of ways this could be improved:
- if it is the kotlin compiler getting confused between the `di` property defined in the `DIAware` interface and the `di` function provided by kodein, perhaps giving these different names might avoid the problem completely. I realise this is a workaround.
- The example code in the documentation could provide the full path in-line (e.g. `by org.kodein.di.android.di()`).
- Provide a footnote in the docs stating "you may need to explicitly import org.kodein.di.android.di".

I'm happy to raise a PR if needed.
