### ISSUE TITLE
Does not represent a scope dependency for the ViewModel

### ISSUE THREAD

**Issue by FasdAR** [Kodein-Framework/Kodein-DI#351]
Kodein does not give a dependency to the viewmodel if it has a scope

```
class ThriftApp: Application(), DIAware
{
    override val di: DI by DI.lazy {
        import(androidXModule(this@ThriftApp))
        import(ciceroneModule)
        bind<String>(tag = "testst") with scoped(activityScope).singleton { UUID.randomUUID().toString() }
    }
}
```

```
val activityScope = WeakContextScope.of<Activity>()
```

```
class InitMainCurrencyViewModel(val app: Application): AndroidViewModel(app), DIAware
{
    override val di: DI by di()
    private val testString: String by instance(tag = "testst")

    fun test() {
        val referenceValue = Integer.toHexString(System.identityHashCode(testString))
        Log.d("SCOPE_TEST_VM", "$testString $referenceValue")
    }
}
```

Log Error:
```
2021-01-09 08:19:11.340 11249-11249/com.fasdev.thriftbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fasdev.thriftbox, PID: 11249
    org.kodein.di.DI$NotFoundException: No binding found for bind<String>(tag = "testst") with ?<InitMainCurrencyViewModel>().? { ? }
    Available bindings for this type:
            bind<String>(tag = "testst") with scoped(WeakContextScope.Of).singleton { String }
            module ⁣androidModule {
                bind<String>(tag = "packageResourcePath") with contexted<Context>().provider { String }
                bind<String>(tag = "packageCodePath") with contexted<Context>().provider { String }
                bind<String>(tag = "packageName") with contexted<Context>().provider { String }
            }
    Registered in this DI container:
            bind<String>(tag = "testst") with scoped(WeakContextScope.Of).singleton { String }
            module cicerone {
                bind<NavigatorHolder>() with scoped(WeakContextScope.Of).singleton { NavigatorHolder }
                bind<Router>() with scoped(WeakContextScope.Of).singleton { Router }
                bind<Cicerone<Router>>() with scoped(WeakContextScope.Of).singleton { Cicerone<Router> }
            }
            module ⁣androidModule {
                bind<NetworkStatsManager>() with contexted<Context>().provider { NetworkStatsManager }
                bind<PrintManager>() with contexted<Context>().provider { PrintManager }
                bind<DisplayManager>() with contexted<Context>().provider { DisplayManager }
                bind<AppOpsManager>() with contexted<Context>().provider { AppOpsManager }
                bind<WifiManager>() with contexted<Context>().provider { WifiManager }
                bind<FingerprintManager>() with contexted<Context>().provider { FingerprintManager }
                bind<Resources.Theme>() with contexted<Context>().provider { Resources.Theme }
                bind<UiModeManager>() with contexted<Context>().provider { UiModeManager }
                bind<AssetManager>() with contexted<Context>().provider { AssetManager }
                bind<CameraManager>() with contexted<Context>().provider { CameraManager }
                bind<InputMethodManager>() with contexted<Context>().provider { InputMethodManager }
                bind<String>(tag = "packageResourcePath") with contexted<Context>().provider { String }
                bind<DevicePolicyManager>() with contexted<Context>().provider { DevicePolicyManager }
                bind<SensorManager>() with contexted<Context>().provider { SensorManager }
                bind<BatteryManager>() with contexted<Context>().provider { BatteryManager }
                bind<LocationManager>() with contexted<Context>().provider { LocationManager }
                bind<File>(tag = "obb") with contexted<Context>().provider { File }
                bind<String>(tag = "packageCodePath") with contexted<Context>().provider { String }
                bind<DownloadManager>() with contexted<Context>().provider { DownloadManager }
                bind<String>(tag = "packageName") with contexted<Context>().provider { String }
                bind<Application>() with provider { Application }
                bind<AudioManager>() with contexted<Context>().provider { AudioManager }
                bind<Resources>() with contexted<Context>().provider { Resources }
                bind<ActivityManager>() with contexted<Context>().provider { ActivityManager }
                bind<ClipboardManager>() with contexted<Context>().provider { ClipboardManager }
                bind<WindowManager>() with contexted<Context>().provider { WindowManager }
                bind<ContentResolver>() with contexted<Context>().provider { ContentResolver }
                bind<WifiP2pManager>() with contexted<Context>().provider { WifiP2pManager }
                bind<AppWidgetManager>() with contexted<Context>().provider { AppWidgetManager }
                bind<File>(tag = "cache") with contexted<Context>().provider { File }
                bind<WallpaperManager>() with contexted<Context>().provider { WallpaperManager }
                bind<AlarmManager>() with contexted<Context>().provider { AlarmManager }
2021-01-09 08:19:11.340 11249-11249/com.fasdev.thriftbox E/AndroidRuntime:             bind<AccountManager>() with contexted<Context>().provider { AccountManager }
                bind<MediaRouter>() with contexted<Context>().provider { MediaRouter }
                bind<AccessibilityManager>() with contexted<Context>().provider { AccessibilityManager }
                bind<ConnectivityManager>() with contexted<Context>().provider { ConnectivityManager }
                bind<SharedPreferences>() with contexted<Context>().provider { SharedPreferences }
                bind<SharedPreferences>() with contexted<Context>().factory { String -> SharedPreferences }
                bind<NsdManager>() with contexted<Context>().provider { NsdManager }
                bind<TvInputManager>() with contexted<Context>().provider { TvInputManager }
                bind<CarrierConfigManager>() with contexted<Context>().provider { CarrierConfigManager }
                bind<MidiManager>() with contexted<Context>().provider { MidiManager }
                bind<TelecomManager>() with contexted<Context>().provider { TelecomManager }
                bind<UsageStatsManager>() with contexted<Context>().provider { UsageStatsManager }
                bind<ShortcutManager>() with contexted<Context>().provider { ShortcutManager }
                bind<DropBoxManager>() with contexted<Context>().provider { DropBoxManager }
                bind<StorageManager>() with contexted<Context>().provider { StorageManager }
                bind<PackageManager>() with contexted<Context>().provider { PackageManager }
                bind<NotificationManager>() with contexted<Context>().provider { NotificationManager }
                bind<LayoutInflater>() with contexted<Context>().provider { LayoutInflater }
                bind<JobScheduler>() with contexted<Context>().provider { JobScheduler }
                bind<Looper>() with contexted<Context>().provider { Looper }
                bind<UsbManager>() with contexted<Context>().provider { UsbManager }
                bind<TelephonyManager>() with contexted<Context>().provider { TelephonyManager }
                bind<BluetoothManager>() with contexted<Context>().provider { BluetoothManager }
                bind<SystemHealthManager>() with contexted<Context>().provider { SystemHealthManager }
                bind<HardwarePropertiesManager>() with contexted<Context>().provider { HardwarePropertiesManager }
                bind<ConsumerIrManager>() with contexted<Context>().provider { ConsumerIrManager }
                bind<File>(tag = "files") with contexted<Context>().provider { File }
                bind<NfcManager>() with contexted<Context>().provider { NfcManager }
                bind<TextServicesManager>() with contexted<Context>().provider { TextServicesManager }
                bind<UserManager>() with contexted<Context>().provider { UserManager }
                bind<InputManager>() with contexted<Context>().provider { InputManager }
                bind<ApplicationInfo>() with contexted<Context>().provider { ApplicationInfo }
                bind<SearchManager>() with contexted<Context>().provider { SearchManager }
                bind<MediaProjectionManager>() with contexted<Context>().provider { MediaProjectionManager }
                bind<CaptioningManager>() with contexted<Context>().provider { CaptioningManager }
                bind<RestrictionsManager>() with contexted<Context>().provider { RestrictionsManager }
                bind<LauncherApps>() with contexted<Context>().provider { LauncherApps }
                bind<SubscriptionManager>() with contexted<Context>().provider { SubscriptionManager }
                bind<MediaSessionManager>() with contexted<Context>().provider { MediaSessionManager }
                bind<Vibrator>() with contexted<Context>().provider { Vibrator }
                bind<KeyguardManager>() with contexted<Context>().provider { KeyguardManager }
                bind<PowerManager>() with contexted<Context>().provider { PowerManager }
            }
    
        at org.kodein.di.internal.DIContainerImpl.factory(DIContainerImpl.kt:187)
        at org.kodein.di.DIContainer$DefaultImpls.factory$default(DIContainer.kt:32)
2021-01-09 08:19:11.343 11249-11249/com.fasdev.thriftbox E/AndroidRuntime:     at org.kodein.di.DIContainer$DefaultImpls.provider(DIContainer.kt:76)
        at org.kodein.di.internal.DIContainerImpl.provider(DIContainerImpl.kt:6)
        at org.kodein.di.DIContainer$DefaultImpls.provider$default(DIContainer.kt:75)
        at org.kodein.di.DIAwareKt$Instance$1.invoke(DIAware.kt:176)
        at org.kodein.di.DIAwareKt$Instance$1.invoke(Unknown Source:4)
        at org.kodein.di.DIProperty$provideDelegate$1.invoke(properties.kt:44)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.fasdev.thriftbox.ui.view.fragment.initMainCurrency.InitMainCurrencyViewModel.getTestString(Unknown Source:7)
        at com.fasdev.thriftbox.ui.view.fragment.initMainCurrency.InitMainCurrencyViewModel.test(InitMainCurrencyViewModel.kt:19)
        at com.fasdev.thriftbox.ui.view.fragment.initMainCurrency.InitMainCurrencyFragment.onActivityCreated(InitMainCurrencyFragment.kt:62)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2717)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:336)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1186)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2222)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1995)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1951)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

If remove the scope, and leave the singleton it works

**Comment by romainbsl** [comment]
This seems normal. If you bind a scoped dependency, you should inject it with a scope as well.
However, in your example, you inject your UUID like a classic singleton
`private val testString: String by instance(tag = "testst")`
You should have something like:
`private val testString: String by on(activity).instance(tag = "testst")`

But, regarding your code example, I wonder why you are trying to inject something scoped on an activity, inside a view model.

**Comment by romainbsl** [comment]
Closing. Don't hesitate to reopen if needed.
